# Generated by Django 2.2 on 2020-12-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WellOiled_App', '0002_register_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('comp_level', models.CharField(max_length=8)),
                ('home_office', models.CharField(max_length=100)),
                ('initial_password', models.CharField(max_length=45)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellOiled_App.Register')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smltap', models.BooleanField(default=False)),
                ('lrgtap', models.BooleanField(default=False)),
                ('smlcomp', models.BooleanField(default=False)),
                ('lrgcomp', models.BooleanField(default=False)),
                ('iso', models.BooleanField(default=False)),
                ('highp', models.BooleanField(default=False)),
                ('angle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellOiled_App.Employee')),
            ],
        ),
    ]
