# Generated by Django 2.2 on 2020-12-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellOiled_App', '0003_employee_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='angle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='highp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='iso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='lrgcomp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='lrgtap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='smlcomp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='smltap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
