# Generated by Django 2.2 on 2020-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellOiled_App', '0004_auto_20201208_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap', models.BooleanField(default=False)),
                ('plug', models.BooleanField(default=False)),
                ('isolate', models.BooleanField(default=False)),
                ('psi', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('angle', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=255)),
                ('jobstart', models.DateField()),
                ('jobend', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ManyToManyField(related_name='jobparameters', to='WellOiled_App.Employee')),
            ],
        ),
    ]
