# Generated by Django 2.2 on 2020-12-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellOiled_App', '0007_auto_20201210_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='highp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lrgcomp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lrgtap',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='smlcomp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='smltap',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
